# Generated by Django 2.2.1 on 2019-05-08 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, verbose_name='课程编号')),
                ('cname', models.CharField(max_length=32, verbose_name='课程名称')),
                ('teacher_name', models.CharField(max_length=32, verbose_name='授课老师')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('suitable_grade', models.IntegerField(verbose_name='课程适合年级')),
                ('cancle_year', models.IntegerField(blank=True, null=True, verbose_name='取消年份')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='学号')),
                ('sname', models.CharField(max_length=32, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='性别')),
                ('inage', models.IntegerField(verbose_name='入学年龄')),
                ('inyear', models.IntegerField(verbose_name='入学年份')),
                ('sclass', models.CharField(max_length=32, verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='选课年份')),
                ('score', models.IntegerField(verbose_name='成绩')),
                ('course_cid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Course', verbose_name='课程编号')),
                ('student_sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='学生学号')),
            ],
            options={
                'verbose_name': '选课信息',
                'verbose_name_plural': '选课信息',
            },
        ),
    ]
